version: "3"
services:
    watcher:
        build:
            context: .
        volumes:
            - ${PWD}/script:/script
            # Map watched directories. Map each watched directory to /dir/1, dir/2, and so on.
            - ${PWD}/watched_dir:/dir/1
            # Example
            #- /home/user/absolute/path:/dir/2
        image: docker-python-watcher