version: "3"
services:
    watcher:
        build:
            context: .
        volumes:
            - ${PWD}/script:/script
            - ${PWD}/dir:/dir/1
            #- /home/user/absolute/path:/dir/2
        image: docker-python-watcher